Document: gdb
Title: Debian gdb Manual
Author: <insert document author here>
Abstract: This manual describes what gdb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gdb/gdb.sgml.gz

Format: postscript
Files: /usr/share/doc/gdb/gdb.ps.gz

Format: text
Files: /usr/share/doc/gdb/gdb.text.gz

Format: HTML
Index: /usr/share/doc/gdb/html/index.html
Files: /usr/share/doc/gdb/html/*.html
